name: Pull Docker Image from ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pull-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 设置环境变量，这里使用的是加密后的密钥
    - name: Set up environment variables
      env:
        ACR_USERNAME: aliyun5694155858
        ACR_PASSWORD: q3231423581

    # 登录到阿里云容器镜像服务
    - name: Login to Alibaba Cloud Container Registry
      run: |
        echo "q3231423581" | docker login --username=aliyun5694155858 crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com

    # 拉取镜像
    - name: Pull Docker image
      run: |
        docker pull crpi-fierbpua1f5su3ae.cn-zhangjiakou.personal.cr.aliyuncs.com/islilacok/learnner:tagname