name: 打包Vue项目

on: push
permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖，项目打包
        run: |
          npm install
          npm run build

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages  # 分支
          github_token: ${{ secrets.DEPLOY_PAT }} # 使用PAT
     
          publish_dir: ./dist # 假设你的构建输出目录是`dist`
          publish_branch: gh-pages # 部署到`gh-pages`分支
          # floder: build # 生产环境文件会在分支的build文件夹里


